### PR TITLE
Bootstrap 5.3.1

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @solomax !
I cherry-picked it to 10.x

**Comment by solomax** [comment]
Please let me know when you are planning release :)

I'll create couple of PR with dependencies updated :)

**Comment by martin-g** [comment]
> Please let me know when you are planning release :)

Whenever one asks me!

Please test the current -SNAPSHOT and if there is no obvious problem then let me know which branch should be released.

**Comment by solomax** [comment]
@martin-g could you please create official `6.0.5-SNAPSHOT`? :)))
testing it using our main app :)

**Comment by martin-g** [comment]
Done!
https://oss.sonatype.org/content/repositories/snapshots/de/agilecoders/wicket/wicket-bootstrap-extensions/6.0.5-SNAPSHOT/

**Pull request merged**
