### PR TITLE
MomentJS webjar coordinates are fixed; Examples are fixed

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @solomax !

**Comment by solomax** [comment]
@martin-g would it be possible to deploy this SNAPSHOT? :)

**Comment by martin-g** [comment]
Which branch ?

**Comment by solomax** [comment]
`wicket-10.x-bootstrap-5.x` please :)

**Comment by martin-g** [comment]
I can't .... :-/
```
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.2:deploy (default-deploy) on project bootstrap-parent: Failed to deploy artifacts: Could not transfer artifact de.agilecoders.wicket:bootstrap-parent:pom:7.0.6 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): status code: 401, reason phrase: Content access is protected by token (401) -> [Help 1]
  
```
Recently I received some emails from Sonatype about deployment changes but they were saying "You have nothing to do"

**Comment by martin-g** [comment]
Reading https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories

**Comment by martin-g** [comment]
It seems the correct docu is https://central.sonatype.org/publish/generate-token/

**Comment by solomax** [comment]
Login to oss.sonartype
Go to profile
Generate token :)

**Comment by solomax** [comment]
Recently did it to deploy wicketstuff :)

**Comment by martin-g** [comment]
Unfortunately it still does not work ...

**Comment by martin-g** [comment]
OK! 7.0.7-SNAPSHOT has been deployed !

**Pull request merged**
