### PR TITLE
Update FontAwesomeSettings.java correct arrow icons

### PR DESCRIPTION
**Pull request by x-paphio**
arrow_left and arrow_right are referencing alignment icons. They should be arrows like up and down

### CODE REVIEW

**Review by ursjoss — APPROVED** [review]
Thanks for finding and fixing this!

**Comment by martin-g** [comment]
Thank you!

**Comment by solomax** [comment]
@martin-g  Shall this one be cherry-picked to `wicket-9.x-bootstrap-5.x` ? :))

**Comment by martin-g** [comment]
> Shall this one be cherry-picked to `wicket-9.x-bootstrap-5.x` ? :))

Done! Thanks!

**Pull request merged**
