### PR TITLE
issue #828: Compilation errors are fixed

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
I got weird test failure, could you please take a look?

**Comment by martin-g** [comment]
like this one https://travis-ci.org/l0rdn1kk0n/wicket-bootstrap/builds/640902883 ?

**Comment by solomax** [comment]
yep :(

**Comment by martin-g** [comment]
Thanks, @solomax !
I will debug it locally!

**Comment by solomax** [comment]
@martin-g is it OK if I do some more code clean-up
(like removing redundant versions in the pom and removing Deprecated code)?

**Comment by martin-g** [comment]
sure!

**Comment by martin-g** [comment]
But give me few mins to fix this issue. It is pom.xml related too

**Comment by martin-g** [comment]
Fixed!

**Pull request merged**
