### PR TITLE
Bug 663: brandImage should be stateless if not set

### PR DESCRIPTION
**Pull request by ursjoss**
https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/663

### CODE REVIEW

**Comment by martin-g** [comment]
Thank you!

**Comment by ursjoss** [comment]
@martin-g Thanks Martin. Out of curiosity - and for a potential next time:

* Should I have rather worked on master instead of the wicket-7.x branch?
* Does it make sense that I opened a bug report besides issueing a pull request?

Thanks and cheers
Urs

**Comment by martin-g** [comment]
> Should I have rather worked on master instead of the wicket-7.x branch?

It's the same for me.


> Does it make sense that I opened a bug report besides issueing a pull request?

There is no need of an issue. PR is just enough. If something is not clear we can discuss in the PR itself.

**Comment by ursjoss** [comment]
Thanks for the clarifications

**Pull request merged**
