### PR TITLE
Dependencies are updated

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
```
[INFO] [stdout]     [ERROR] Failed to execute goal on project wicket-bootstrap-samples: Could not resolve dependencies for project de.agilecoders.wicket:wicket-bootstrap-samples:war:6.0.4: Could not find artifact org.wicketstuff:wicketstuff-annotation:jar:9.14.0 in repo.clojars.org (https://repo.clojars.org) -> [Help 1]
[INFO] [stdout]     [ERROR] 
```

I need to wait for Wicketstuff to become available at Maven Central to be able to release.

**Comment by solomax** [comment]
My bad :( forgot to push `Release` button ...
Should be OK in a minute :)

**Comment by martin-g** [comment]
6.0.4 has been released!
Thank you, @solomax !

**Comment by reckart** [comment]
The project page still shows 0.9.5 to be the latest release. It would be great if somebody with the permissions to do it could go to

* the tags list
* create a new release from the latest tag
* press the button to auto-generate the release notes (possibly setting the base release in the dropdown to 6.0.3 before since there have been no release announcements for so long)
* save

Thanks!

**Comment by reckart** [comment]
Also, it seems that the milestones list could use some attention, either deleting all milestones or creating milestones corresponding to the next planned versions, e.g. 6.0.5 - https://github.com/l0rdn1kk0n/wicket-bootstrap/milestones

**Comment by martin-g** [comment]
This project does not use Github releases and milestones for many years!

**Comment by reckart** [comment]
If milestones are not used, it would be nice to close any remaining open milestones.

It would be really nice if it did use at least the release notes because they provide a nice summary of what changed between versions. 

Years ago, creating release notes was an annoying task and time-consuming task. These days, it is a press of a button.

If it is still desired to not use releases, it might be considered to delete all existing releases or to mark them as pre-releases so that the "latest release" information on the project page does not appear to be terribly outdated.

**Comment by martin-g** [comment]
> If milestones are not used, it would be nice to close any remaining open milestones.

Done!



> Years ago, creating release notes was an annoying task and time-consuming task. These days, it is a press of a button.

Where is this button ?

**Comment by reckart** [comment]
Screenshot 2023-05-30 at 10 33 44

**Comment by reckart** [comment]
AFAIK the functionality relies on PRs. In the projects I am working on almost everything goes in through PRs, so it works very well for me. I hope it works well for this project as well. Let's try ;)

**Comment by martin-g** [comment]
Thanks!

I still don't have time/willingness to do yet another task.
I deleted all previous Github releases.

**Pull request merged**
