### PR TITLE
Czech localization of the BootstrapFileInputField

### PR DESCRIPTION
**Pull request by vrozkovec**
What should I do to propagate this to other branches? Should I create the file in each branch and make a pull request there? Won't there be a problem with branch merging then?

### CODE REVIEW

**Comment by martin-g** [comment]
IMO it would be better to use the XML variant of resource bundle because it works better for non-ASCII characters. See https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/Application_bg.properties.xml for example.

**Comment by martin-g** [comment]
> What should I do to propagate this to other branches? Should I create the file in each branch and make a pull request there? Won't there be a problem with branch merging then?

Since your change is in `wicket-8.x` branch I will `cherry-pick` it in `master` and `wicket-7.x`. If it was in `master` then I would use `git merge`.

**Comment by vrozkovec** [comment]
Now I see it is not really tied to the component, as res/fileinput.tmpl.js here makes no use of those variables:
```
PackageTextTemplate tmpl = new PackageTextTemplate(BootstrapFileInputField.class, "res/fileinput.tmpl.js");
Map<String, Object> variables = new HashMap<>();
variables.put("markupId", Strings2.getMarkupId(this));
for (String label : LABELS) {
    variables.put(label, getString(label));
}
variables.put("eventName", ajaxUploadBehavior.getEvent());

ajaxUpload = tmpl.asString(variables);

```

**Comment by vrozkovec** [comment]
I can close this pull request and commit to the master then, if that's easier

**Comment by vrozkovec** [comment]
Ok, I'll change it to the .xml version and commit to the master

**Comment by vrozkovec** [comment]
Done here: #661 
closing this pull request

**Pull request closed without merging**
