### PR TITLE
Moving to wicket-10, initial commit

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
@martin-g PR incomplete

Tests fail with
```
java.lang.NoClassDefFoundError: org/apache/wicket/util/time/Duration
	at de.agilecoders.wicket.jquery.util.CharSequenceWrapper.toParameterValue(CharSequenceWrapper.java:73)
	at de.agilecoders.wicket.jquery.function.AbstractFunction.toParameterValue(AbstractFunction.java:72)
```

**Comment by solomax** [comment]
Blocked by now :(

**Comment by martin-g** [comment]
As I said in the issue you will need new versions for wicket-webjars and wicket-jquery-selectors too because they bring Wicket 9.x as dependency:

in the parent pom.xml:
```
   <wicket-webjars.version>3.0.6</wicket-webjars.version>
        <wicket-jquery-selectors.version>3.0.4</wicket-jquery-selectors.version>
```

**Comment by solomax** [comment]
Shall I create PRs for these jars as well? or maybe you can release new versions? :)

**Comment by solomax** [comment]
@martin-g I'll try to create PRs, will start with `wicket-webjars`

**Comment by martin-g** [comment]
Yes, this works better!
Someone creates the PRs and I just merge them! :-)
For a person who does not do any Java coding since few years I am doing great, no? :-)

**Comment by solomax** [comment]
> For a person who does not do any Java coding since few years I am doing great, no? :-)

I don't believe you :)))

**Comment by martin-g** [comment]
https://oss.sonatype.org/content/repositories/snapshots/de/agilecoders/wicket/wicket-bootstrap-extensions/7.0.0-SNAPSHOT/

**Comment by solomax** [comment]
many thanks! :)

**Pull request merged**
