### PR TITLE
Wicket 8.x bootstrap 4.x

### PR DESCRIPTION
**Pull request by helmut8080**
AlignmentBehavior final for Alignment Model added

### CODE REVIEW

**Comment by helmut8080** [comment]
Only AlignmentBehavior needs to be committed. Colapsible.html and Collapsible.java were already committed.

**Comment by martin-g** [comment]
> Only AlignmentBehavior needs to be committed. Colapsible.html and Collapsible.java were already committed.

What do you mean with that ?
`AlignmentBehavior` has only one simple change of making a field `final`.

**Comment by helmut8080** [comment]
Sorry. I had difficulties with git reject this commit.

**Comment by martin-g** [comment]
What is `git reject` ? :-)

I'm closing this PR because there are no changes in it anymore (after your local update).

**Pull request closed without merging**
