### PR TITLE
Cross-grade to jsass 5.11.0

### PR DESCRIPTION
**Pull request by reckart**

### CODE REVIEW

**Comment by martin-g** [comment]
Thank you, @reckart !

**Comment by reckart** [comment]
@martin-g would you cherry-pick it into the other relevant branches as well?

**Comment by martin-g** [comment]
which ones ?

**Comment by reckart** [comment]
TBH, I am a bit confused about the branches a bit.

The PR I made was against the 9.x-bs-5 branch. But there is also the wicket-9.x default branch, the 9.x-bs-4 branch and of course the 10.x-bs-5 branch. 

How about making the 9.x-bs-5 the default branch?

I guess the change should be cherry-picked or up-merged at least into the 10.x-bs-5 branch.

**Comment by reckart** [comment]
Oh and there is the "master" branch as well...

**Comment by martin-g** [comment]
I do not own the repository and I cannot make such kind of changes.
I just merge people's PRs and cut releases :-)

**Comment by reckart** [comment]
@martin-g maybe you need a permission upgrade from the owner ;)

**Comment by martin-g** [comment]
I haven't thought about this before :-) Or did I ?! Well, I still don't have permissions ...

**Comment by reckart** [comment]
@l0rdn1kk0n ping?

**Pull request merged**
