### PR TITLE
animate.css

### PR DESCRIPTION
**Pull request by danjee**
Added animate.css to wicket-bootstrap

### CODE REVIEW

**Comment by martin-g** [comment]
Thank you!

**Comment by martin-g** [comment]
We need to add a demo of it in the -samples project.

**Comment by tahitiangabriel** [comment]
Shouldn't it be in bootstrap-extensions rather than in bootsrap-core?

**Comment by martin-g** [comment]
Ah, I didn't notice this!
Right. It should be in -extensions.

**Comment by danjee** [comment]
I've added in the core next to the BadgeBehavior, QuoteBehavior and other Behavior implementations. 
I will also add a demo for it

**Comment by martin-g** [comment]
-core contains only things coming from http://getbootstrap.com/.
-extensions is for third party addons.
Animate.css is not Bootstrap related but I think it is OK to have here because it could make the components even more awesome.

**Comment by danjee** [comment]
I see. I will make only modifications in the samples pages then.

**Comment by tahitiangabriel** [comment]
If it stays in the core you are adding a dependancy to org.webjars.animate.css which most people won't use.
And core dev would have to mainain it for ever! ;-)
As it is a third party addon it should be in the extension module. It would be cleaner.
My 2 cents.

**Comment by martin-g** [comment]
@danjee Please move it from -core to -extensions if you have time.
Otherwise I'll do it the next days.

**Comment by danjee** [comment]
Ok, I will move it in the next commit with samples.
Thanks Martin and Gabriel

**Pull request merged**
