### PR TITLE
Basic rtl

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by reckart** [comment]
It seems that the PR contains a separate version of the compiled bootstrap for RTL languages. Is that observation correct?

**Comment by solomax** [comment]
@reckart yes, bootstrap should be updated before merge (webjar release is not available her)

**Comment by reckart** [comment]
By updated you mean removed? Why are would separate fully compiled Bootstrap CSS files for RTL and non-RTL be required? Looking at the Bootstrap documentation, the main change towards RTL support in BS5 was to replace the `XXX-left`/`XXX-right` classes with `XXX-start` and `XXX-end`(e.g. `ml-1` -> `ms-1`). I don't see indications that vanilla BS has any type of build-time switch for RTL-related properties.

**Comment by reckart** [comment]
Ah, ok... now I see. The included `bootstrap.rtl.css` is actually part of the upstream distro. I wasn't aware of that: 

https://getbootstrap.com/docs/5.3/getting-started/contents/#css-files

**Comment by solomax** [comment]
@reckart was just about to paste same link :))

**Comment by reckart** [comment]
@solomax Actually, The BS 5.3.1 webjar is available on Maven Central: https://search.maven.org/artifact/org.webjars.npm/bootstrap/5.3.1/jar

Unzipping the file, I can also see the RTL variations of the CSS files in there.

**Comment by solomax** [comment]
Thanks!
I'll update this pr with new bootstrap a bit later tonight :)

https://mvnrepository.com/artifact/org.webjars/bootstrap displays outdated info :(

**Comment by solomax** [comment]
Maven coordinates are wrong :(

we are using `org.webjars:bootstrap` while at your link the artifact is `org.webjars.npm:bootstrap`

I've created an issue: https://github.com/webjars/bootstrap/issues/184

**Comment by reckart** [comment]
Any reason not to use the `org.webjars.npm` version?

According to https://www.webjars.org, the `org.webjars.npm` version mirrors the contents of the respective NPM package whereas `org.webjars` must be manually built and deployed - seems unnecessary overhead?

**Comment by reckart** [comment]
Also, if a new version of an `org.webjars.npm` package is required, it appears this can be done directly from the webjars website using the `Add webjar...` button, just by entering the package name and selecting the version desired.

**Comment by solomax** [comment]
> Any reason not to use the org.webjars.npm version?

These jars have different structure
Maybe resource load will miss in case `org.webjars.npm:bootstrap` will be used

Anyway this question is for another PR :)))

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @solomax !

**Comment by solomax** [comment]
@martin-g could you please cherry-pick this one to wicket-10 branch? :)

**Comment by martin-g** [comment]
Done!

**Comment by solomax** [comment]
@martin-g for whatever reason I don't see this commit here: https://github.com/l0rdn1kk0n/wicket-bootstrap/commits/wicket-10.x-bootstrap-5.x :(((

**Comment by martin-g** [comment]
It was my fault. Just pushed it.

**Comment by solomax** [comment]
Thanks! :)))

**Pull request merged**
