### PR TITLE
Adding new signature to install to allow for custom WebjarSettings

### PR DESCRIPTION
**Pull request by heryqk**
This change will allow user to provide a WebSphereWebjarSettings config to Bootstrap.install().

### CODE REVIEW

**Comment by martin-g** [comment]
Please check my solution based on Builder API.
If it works well I will release a new version!

**Comment by heryqk** [comment]
@martin-g  Seems to work very well. I like the implementation. Are you releasing wicket-webjars 0.4.10 first and including it in wicket-bootstrap 0.9.18 ?

**Comment by martin-g** [comment]
Sure!

**Comment by martin-g** [comment]
They are released and being copied to Maven Central!
I'll announce them tomorrow.
Enjoy! :-)

**Comment by heryqk** [comment]
Awesome ! Thank you !

**Comment by heryqk** [comment]
@martin-g Have the artifacts been copied to Maven Central ? I can't find them.

**Comment by martin-g** [comment]
http://repo1.maven.org/maven2/de/agilecoders/wicket/wicket-bootstrap-core/0.9.18/
http://repo1.maven.org/maven2/de/agilecoders/wicket/webjars/wicket-webjars/0.4.9/

**Pull request closed without merging**
