### PR TITLE
Dependencies are updated

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
@solomax This is ready, right ? Do I need to wait for something ?

**Comment by solomax** [comment]
@martin-g as far as I can tell we are good to release :)

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
6.0.3 has been released and on its way to Maven Central.

**Comment by solomax** [comment]
Thanks @martin-g ! :))

**Pull request merged**
