### PR TITLE
Confirmation : Update JS version to 2.2.0 + be able to use a JQ selector for singleton

### PR DESCRIPTION
**Pull request by tahitiangabriel**
Add a constructor to give a JQ selector instead of the component ID to
be able to use singleton's option.

### CODE REVIEW

**Comment by martin-g** [comment]
There are some whitespace issues and the diff says "replace the whole file".
I'll merge it in a temporary branch to undo them.
Thanks, @tahitiangabriel !

**Comment by tahitiangabriel** [comment]
Sorry for the whitepaces. I don't know what is going on. It's fine in eclipse and when I commit to github it is not anymore!

**Comment by tahitiangabriel** [comment]
@martin-g This should be fine with the latest commit.
I guess you don't care about the JS files, do you?

**Comment by martin-g** [comment]
Perfect!
Thanks!

**Pull request merged**
