### PR TITLE
Czech localization for the BootstrapFileInputField

### PR DESCRIPTION
**Pull request by vrozkovec**

### CODE REVIEW

**Comment by vrozkovec** [comment]
Committing still, to have it ready when localization works.

**Comment by martin-g** [comment]
The file extension should be `.properties.xml`.

**Comment by martin-g** [comment]
From https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/660#issuecomment-282277243 I understand that this won't really work, right ?
Do you want to extend the PR to make it working ?

**Comment by vrozkovec** [comment]
I'll see what I can do

**Comment by vrozkovec** [comment]
I see the picker itself support localization: http://plugins.krajee.com/file-input#translations. I'll add that to the config. Closing this request as .properties are not necessary anymore.

**Pull request closed without merging**
