### PR TITLE
BootstrapFileInputField fixes

### PR DESCRIPTION
**Pull request by vrozkovec**
Fixed localization option name
Error propagation from behavior to the field

### CODE REVIEW

**Comment by martin-g** [comment]
Thank you!

**Comment by vrozkovec** [comment]
Thanks. How do you proceed now, when can be those changes seen in the wicket 8.x branch?

**Comment by martin-g** [comment]
I was gong to merge them soon but I'll do it now since you need them!

**Comment by vrozkovec** [comment]
Oh, thanks, don't worry that much, I've deployed my local snapshot already :)
I just asked to know what is the process. Thank you!

**Comment by martin-g** [comment]
Done!

**Pull request merged**
