### PR TITLE
font-awesome is updated

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — CHANGES_REQUESTED** [review]
Please update https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-9.x-bootstrap-5.x/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/icon/FontAwesome5CDNCSSReference.java#L21 too

**Comment by ursjoss** [comment]
I will provide an update of the icon classes in a separate PR later this week.

**Comment by solomax** [comment]
Hopefully all versions are updated ;)

**Review by martin-g — APPROVED** [review]

**Comment by solomax** [comment]
@martin-g can you publish new SNAPSHOT please? :)

**Comment by martin-g** [comment]
Done!

**Pull request merged**
