### PR TITLE
test refactoring wicket-9.x

### PR DESCRIPTION
**Pull request by ursjoss**
* access modifiers in junit 5
  * use some lambdas instead of anonymous classes
  * diamond operators

### CODE REVIEW

**Comment by ursjoss** [comment]
@martin-g Note, I did merge `wicket-8.x` into the PR branch with the intention of resolving merge issues. Obviously this pulled in some commits that had not yet been applied to wicket-9.x. Please verify.

If you'd rather not mix this PR with the merge, let me know. I'd then revert the merge and force push this branch.

**Comment by martin-g** [comment]
Yes, it seems something is not good here. I will check it later.

**Comment by ursjoss** [comment]
I reset back to before the merge. I should not have mixed that anyway. Sorry for the noise and the force-push. :-/

**Comment by martin-g** [comment]
Thank you, @ursjoss !

**Comment by martin-g** [comment]
If you need a release of any of the branches just let me know!

**Comment by ursjoss** [comment]
@martin-g Thanks for merging. No need to release for those PRs.

**Pull request merged**
